name: control_gastos_carros
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  bloc: ^8.1.2
  bloc_test: ^9.1.5
  collection: ^1.17.2
  datetime_picker_formfield_new: ^2.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_search_bar: ^3.0.0-dev.1
  intl: ^0.18.1
  mockito: ^5.4.3
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+3
  sqflite_common_ffi_web: ^0.4.0
  sqlite3: ^2.1.0
  syncfusion_flutter_charts: ^23.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
